source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'





target 'RealmJSONDemo' do
  pod 'AFNetworking'
  pod 'Realm+JSON', :path => '../'

    target 'RealmJSONDemoTests' do
    end

end
